[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"

[[redirects]]
  from = "/posts/redefining-monitoring-netdata"
  to = "/redefining-monitoring-with-netdata"

[[redirects]]
  from = "/posts/*"
  to = "https://www.netdata.cloud/blog/:splat"
  force = true

# Non-wildcard tag redirects
[[redirects]]
  from = "/tags/k-8-s/"
  to = "https://www.netdata.cloud/tags/k8s/"
  force = true

[[redirects]]
  from = "/tags/free-bsd/"
  to = "https://www.netdata.cloud/tags/freebsd/"
  force = true

[[redirects]]
  from = "/tags/bind-9/"
  to = "https://www.netdata.cloud/tags/bind9/"
  force = true

[[redirects]]
  from = "/tags/bind-9/"
  to = "https://www.netdata.cloud/tags/bind9/"
  force = true

[[redirects]]
  from = "/tags/co-2/"
  to = "https://www.netdata.cloud/tags/co2/"
  force = true

[[redirects]]
  from = "/tags/pm-1/"
  to = "https://www.netdata.cloud/tags/pm1/"
  force = true

[[redirects]]
  from = "/tags/pm-25/"
  to = "https://www.netdata.cloud/tags/pm25/"
  force = true

[[redirects]]
  from = "/tags/pop-3/"
  to = "https://www.netdata.cloud/tags/pop3/"
  force = true

[[redirects]]
  from = "/tags/postgre-sql/"
  to = "https://www.netdata.cloud/tags/postgresql/"
  force = true

[[redirects]]
  from = "/tags/s-m-a-r-t/"
  to = "https://www.netdata.cloud/tags/s.m.a.r.t/"
  force = true

[[redirects]]
  from = "/tags/server/"
  to = "https://www.netdata.cloud/tags/server-monitoring/"
  force = true

[[redirects]]
  from = "/tags/smartd-log/"
  to = "https://www.netdata.cloud/tags/smartd_log/"
  force = true

[[redirects]]
  from = "/tags/"
  to = "https://www.netdata.cloud/blog/"
  force = true

# Wildcard tag redirect
[[redirects]]
  from = "/tags/*"
  to = "https://www.netdata.cloud/tags/:splat"
  force = true

# Non-wildcard blog post redirects
[[redirects]]
  from = "/exploring-systemd-journal-logs-with-netdata/"
  to = "https://www.netdata.cloud/blog/exploring-systemd-journal-logs/"
  force = true

[[redirects]]
  from = "/how-netdatas-machine-learning-works/"
  to = "https://www.netdata.cloud/blog/how-netdatas-ml-based-anomaly-detection-works/"
  force = true

[[redirects]]
  from = "/netdata-qos-classes-monitoring/"
  to = "https://www.netdata.cloud/blog/netdata-qos-monitoring/"
  force = true

[[redirects]]
  from = "/systemd-journal-logs-a-game-changer-for-devops-and-developers/"
  to = "https://www.netdata.cloud/blog/systemd-journal-logs/"
  force = true

[[redirects]]
  from = "/archive/"
  to = "https://www.netdata.cloud/blog/"
  force = true

# Wildcard blog post redirect
[[redirects]]
  from = "/*"
  to = "https://www.netdata.cloud/blog/:splat"
  force = true