[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"

[[redirects]]
  from = "/posts/redefining-monitoring-netdata"
  to = "/redefining-monitoring-with-netdata"

[[redirects]]
  from = "/posts/*"
  to = "/:splat"

# Non-wildcard tag redirects
[[redirects]]
  from = "/tags/bind-9/"
  to = "https://www.netdata.cloud/tags/bind9/"
  force = true

[[redirects]]
  from = "/tags/co-2/"
  to = "https://www.netdata.cloud/tags/co2/"
  force = true

[[redirects]]
  from = "/tags/pm-1/"
  to = "https://www.netdata.cloud/tags/pm1/"
  force = true

[[redirects]]
  from = "/tags/pm-25/"
  to = "https://www.netdata.cloud/tags/pm25/"
  force = true

[[redirects]]
  from = "/tags/pop-3/"
  to = "https://www.netdata.cloud/tags/pop3/"
  force = true

[[redirects]]
  from = "/tags/postgre-sql/"
  to = "https://www.netdata.cloud/tags/postgresql/"
  force = true

[[redirects]]
  from = "/tags/s-m-a-r-t/"
  to = "https://www.netdata.cloud/tags/s.m.a.r.t/"
  force = true

[[redirects]]
  from = "/tags/server/"
  to = "https://www.netdata.cloud/tags/server-monitoring/"
  force = true

[[redirects]]
  from = "/tags/smartd-log/"
  to = "https://www.netdata.cloud/tags/smartd_log/"
  force = true

# Wildcard tag redirect
[[redirects]]
  from = "/tags/*"
  to = "https://www.netdata.cloud/tags/:splat"
  force = true

# Non-wildcard blog post redirects
[[redirects]]
  from = "/exploring-systemd-journal-logs-with-netdata/"
  to = "https://www.netdata.cloud/blog/exploring-systemd-journal-logs/"
  force = true

[[redirects]]
  from = "/how-netdatas-machine-learning-works/"
  to = "https://www.netdata.cloud/blog/how-netdatas-ml-based-anomaly-detection-works/"
  force = true

[[redirects]]
  from = "/netdata-qos-classes-monitoring/"
  to = "https://www.netdata.cloud/blog/netdata-qos-monitoring/"
  force = true

[[redirects]]
  from = "/systemd-journal-logs-a-game-changer-for-devops-and-developers/"
  to = "https://www.netdata.cloud/blog/systemd-journal-logs/"
  force = true

# Temporary prevention of redirect for 404 blog posts
[[redirects]]
  from = "/anomaly-rate-in-every-chart/"
  to = "https://www.netdata.cloud/blog/anomaly-rate-in-every-chart/"
  force = false

[[redirects]]
  from = "/anomaly-rates-in-the-menu/"
  to = "https://www.netdata.cloud/blog/anomaly-rates-in-the-menu/"
  force = false

[[redirects]]
  from = "/cassandra-monitoring-part1/"
  to = "https://www.netdata.cloud/blog/cassandra-monitoring-part1/"
  force = false

[[redirects]]
  from = "/cassandra-monitoring-part2/"
  to = "https://www.netdata.cloud/blog/cassandra-monitoring-part2/"
  force = false

[[redirects]]
  from = "/cncf-live-power-up-your-machine-learning-automated-anomaly-detection/"
  to = "https://www.netdata.cloud/blog/cncf-live-power-up-your-machine-learning-automated-anomaly-detection/"
  force = false

[[redirects]]
  from = "/extending-anomaly-detection-training-window/"
  to = "https://www.netdata.cloud/blog/extending-anomaly-detection-training-window/"
  force = false

[[redirects]]
  from = "/freebsd-monitoring/"
  to = "https://www.netdata.cloud/blog/freebsd-monitoring/"
  force = false

[[redirects]]
  from = "/introducing-anomaly-advisor-unsupervised-anomaly-detection-in-netdata/"
  to = "https://www.netdata.cloud/blog/introducing-anomaly-advisor-unsupervised-anomaly-detection-in-netdata/"
  force = false

[[redirects]]
  from = "/kubernetes-throttling-doesnt-have-to-suck-let-us-help/"
  to = "https://www.netdata.cloud/blog/kubernetes-throttling-doesnt-have-to-suck-let-us-help/"
  force = false

[[redirects]]
  from = "/monitoring-without-cooperation-kubernetes/"
  to = "https://www.netdata.cloud/blog/monitoring-without-cooperation-kubernetes/"
  force = false

[[redirects]]
  from = "/netdata-cost-transparency-unveiling-the-false-cost-of-monitoring/"
  to = "https://www.netdata.cloud/blog/netdata-cost-transparency-unveiling-the-false-cost-of-monitoring/"
  force = false

[[redirects]]
  from = "/netdata-version-1.37/"
  to = "https://www.netdata.cloud/blog/netdata-version-1.37/"
  force = false

[[redirects]]
  from = "/netdata-version-1.38/"
  to = "https://www.netdata.cloud/blog/netdata-version-1.38/"
  force = false

[[redirects]]
  from = "/netdata-version-1.39/"
  to = "https://www.netdata.cloud/blog/netdata-version-1.39/"
  force = false

[[redirects]]
  from = "/netdata-version-1.40/"
  to = "https://www.netdata.cloud/blog/netdata-version-1.40/"
  force = false

[[redirects]]
  from = "/netdata-version-1.41/"
  to = "https://www.netdata.cloud/blog/netdata-version-1.41/"
  force = false

[[redirects]]
  from = "/our-approach-to-machine-learning/"
  to = "https://www.netdata.cloud/blog/our-approach-to-machine-learning/"
  force = false

[[redirects]]
  from = "/server-load/"
  to = "https://www.netdata.cloud/blog/server-load/"
  force = false

[[redirects]]
  from = "/the-netdata-way-of-troubleshooting/"
  to = "https://www.netdata.cloud/blog/the-netdata-way-of-troubleshooting/"
  force = false

[[redirects]]
  from = "/troubleshooting-alerts/"
  to = "https://www.netdata.cloud/blog/troubleshooting-alerts/"
  force = false

# Wildcard blog post redirect
[[redirects]]
  from = "/*"
  to = "https://www.netdata.cloud/blog/:splat"
  force = true